# 这个配置文件是可以直接安装两个不同的odoo
# 这里是nginx的拉取
nginx:
# nginx的版本
    image: nginx:1.14-alpine
    ports:
        - 80:80
        - 443:443
    volumes:
      - /var/www:/var/www
      - /etc/nginx:/etc/nginx
      - /home/letsencrypt/etc/letsencrypt/:/data/certs
      - /home/letsencrypt/data/letsencrypt:/data/letsencrypt
    links:
      - odoo-prod:odoo-prod
      - odoo-dev:odoo-dev
    restart: always
postgres-prod:
# 这里11是pg数据库的版本号，根据自己喜欢填写版本
    image: postgres:11
    environment:
# 数据库用户名称
        - POSTGRES_USER=odoo
# 数据库密码
        - POSTGRES_PASSWORD=aaaaaaaaa
    volumes:
#/home/prod/postgresql 宿主机的数据库配置文件所在位置
        - /home/prod/postgresql:/var/lib/postgresql/data
odoo-prod:
#odoo的Dockerfile文件所在的目录
    build: /home/docker/odoo12
    links:
#链接到的数据名
        - postgres-prod:db
    volumes:
# 配置文件坐在目录/home/prod/odoo/config
        - /home/prod/odoo/config:/etc/odoo
# odoo的数据文件所在目录
        - /home/prod/odoo/data:/var/lib/odoo
# odoo的第三方模块所在目录/home/prod/odoo/extra-addons
        - /home/prod/odoo/extra-addons:/mnt/extra-addons
postgres-dev:
    image: postgres:9.6.10-alpine
    environment:
        - POSTGRES_USER=odoo
        - POSTGRES_PASSWORD=aaaaaaaaa
    volumes:
        - /home/dev/postgresql:/var/lib/postgresql/data
odoo-dev:
    build: /home/docker/odoo12
    links:
        - postgres-dev:db
    volumes:
        - /home/dev/odoo/config:/etc/odoo
        - /home/dev/odoo/data:/var/lib/odoo
        - /home/dev/odoo/extra-addons:/mnt/extra-addons
